version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: shareaes_server
    env_file:
      - ./config/.env.db
      - ./config/.env
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./app/:/project/app/
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: shareaes_db
    env_file:
      - ./config/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    container_name: shareaes_redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: shareaes_celery
    command: celery -A shareaes worker -l info
    env_file:
      - ./config/.env.db
      - ./config/.env
    volumes:
      - ./app/:/project/app/
    depends_on:
      - db
      - redis
    links:
      - redis
  devcontainer:
    container_name: shareaes_server_dev
    build:
      context: ./app
      dockerfile: ./Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/app/

volumes:
  postgres_data:
