const POST = [
  {
    slug: "android-studio",
    name: "android-studio",
    isPublished: true,
    filePath: "android-studio.md",
    tags: ["android-studio"],
    shortDescription: "android-studio",
  },
  {
    slug: "bash",
    name: "bash",
    isPublished: true,
    filePath: "bash.md",
    tags: ["bash"],
    shortDescription: "bash",
  },
  {
    slug: "c#",
    name: "c#",
    isPublished: true,
    filePath: "c#.md",
    tags: ["c#"],
    shortDescription: "c#",
  },
  {
    slug: "crontab",
    name: "crontab",
    isPublished: true,
    filePath: "crontab.md",
    tags: ["crontab"],
    shortDescription: "crontab",
  },
  {
    slug: "dart",
    name: "dart",
    isPublished: true,
    filePath: "dart.md",
    tags: ["dart"],
    shortDescription: "dart",
  },
  {
    slug: "django",
    name: "django",
    isPublished: true,
    filePath: "django.md",
    tags: ["django"],
    shortDescription: "django",
  },
  {
    slug: "docker",
    name: "docker",
    isPublished: true,
    filePath: "docker.md",
    tags: ["docker"],
    shortDescription: "docker",
  },
  {
    slug: "flask",
    name: "flask",
    isPublished: true,
    filePath: "flask.md",
    tags: ["flask"],
    shortDescription: "flask",
  },
  {
    slug: "flutter",
    name: "flutter",
    isPublished: true,
    filePath: "flutter.md",
    tags: ["flutter"],
    shortDescription: "flutter",
  },
  {
    slug: "GCP",
    name: "GCP",
    isPublished: true,
    filePath: "GCP.md",
    tags: ["GCP"],
    shortDescription: "GCP",
  },
  {
    slug: "gitlab-ci-cd",
    name: "gitlab-ci-cd",
    isPublished: true,
    filePath: "gitlab-ci-cd.md",
    tags: ["gitlab-ci-cd"],
    shortDescription: "gitlab-ci-cd",
  },
  {
    slug: "git",
    name: "git",
    isPublished: true,
    filePath: "git.md",
    tags: ["git"],
    shortDescription: "git",
  },
  {
    slug: "go",
    name: "go",
    isPublished: true,
    filePath: "go.md",
    tags: ["go"],
    shortDescription: "go",
  },
  {
    slug: "heroku-django",
    name: "heroku-django",
    isPublished: true,
    filePath: "heroku-django.md",
    tags: ["heroku-django"],
    shortDescription: "heroku-django",
  },
  {
    slug: "js",
    name: "js",
    isPublished: true,
    filePath: "js.md",
    tags: ["js"],
    shortDescription: "js",
  },
  {
    slug: "LetsEncrypt-certbot",
    name: "LetsEncrypt-certbot",
    isPublished: true,
    filePath: "LetsEncrypt-certbot.md",
    tags: ["LetsEncrypt-certbot"],
    shortDescription: "LetsEncrypt-certbot",
  },
  {
    slug: "linux",
    name: "linux",
    isPublished: true,
    filePath: "linux.md",
    tags: ["linux"],
    shortDescription: "linux",
  },
  {
    slug: "live_from_local",
    name: "live_from_local",
    isPublished: true,
    filePath: "live_from_local.md",
    tags: ["live_from_local"],
    shortDescription: "live_from_local",
  },
  {
    slug: "MD_file",
    name: "MD_file",
    isPublished: true,
    filePath: "MD_file.md",
    tags: ["MD_file"],
    shortDescription: "MD_file",
  },
  {
    slug: "mongo",
    name: "mongo",
    isPublished: true,
    filePath: "mongo.md",
    tags: ["mongo"],
    shortDescription: "mongo",
  },
  {
    slug: ".my_bash",
    name: ".my_bash",
    isPublished: true,
    filePath: ".my_bash.sh",
    tags: [".my_bash"],
    shortDescription: ".my_bash",
  },
  {
    slug: "mysql",
    name: "mysql",
    isPublished: true,
    filePath: "mysql.md",
    tags: ["mysql"],
    shortDescription: "mysql",
  },
  {
    slug: "nginx",
    name: "nginx",
    isPublished: true,
    filePath: "nginx.md",
    tags: ["nginx"],
    shortDescription: "nginx",
  },
  {
    slug: "postgresql",
    name: "postgresql",
    isPublished: true,
    filePath: "postgresql.md",
    tags: ["postgresql"],
    shortDescription: "postgresql",
  },
  {
    slug: "python",
    name: "python",
    isPublished: true,
    filePath: "python.md",
    tags: ["python"],
    shortDescription: "python",
  },
  {
    slug: "react",
    name: "react",
    isPublished: true,
    filePath: "react.md",
    tags: ["react"],
    shortDescription: "react",
  },
  {
    slug: "setup-ubuntu",
    name: "setup-ubuntu",
    isPublished: true,
    filePath: "setup-ubuntu.md",
    tags: ["setup-ubuntu"],
    shortDescription: "setup-ubuntu",
  },
  {
    slug: "supervisor",
    name: "supervisor",
    isPublished: true,
    filePath: "supervisor.md",
    tags: ["supervisor"],
    shortDescription: "supervisor",
  },
  {
    slug: "the-linux-command-line",
    name: "the-linux-command-line",
    isPublished: true,
    filePath: "the-linux-command-line.md",
    tags: ["the-linux-command-line"],
    shortDescription: "the-linux-command-line",
  },
  {
    slug: "vim",
    name: "vim",
    isPublished: true,
    filePath: "vim.md",
    tags: ["vim"],
    shortDescription: "vim",
  },
  {
    slug: "vs-code",
    name: "vs-code",
    isPublished: true,
    filePath: "vs-code.md",
    tags: ["vs-code"],
    shortDescription: "vs-code",
  },
  {
    slug: "vue",
    name: "vue",
    isPublished: true,
    filePath: "vue.md",
    tags: ["vue"],
    shortDescription: "vue",
  },
];

export default POST;
