const POST = [
  {
    slug: "android-studio",
    name: "android-studio",
    isPublished: true,
    // coverImage: "",
    tags: ["android-studio"],
    relatedPosts: [""],
    shortDescription: "android-studio",
  },
  {
    slug: "bash",
    name: "bash",
    isPublished: true,
    // coverImage: "",
    tags: ["bash"],
    relatedPosts: [""],
    shortDescription: "bash",
  },
  {
    slug: "c-sharp",
    name: "c-sharp",
    isPublished: true,
    // coverImage: "",
    tags: ["c-sharp"],
    relatedPosts: [""],
    shortDescription: "c-sharp",
  },
  {
    slug: "crontab",
    name: "crontab",
    isPublished: true,
    // coverImage: "",
    tags: ["crontab"],
    relatedPosts: [""],
    shortDescription: "crontab",
  },
  {
    slug: "dart",
    name: "dart",
    isPublished: true,
    // coverImage: "",
    tags: ["dart"],
    relatedPosts: [""],
    shortDescription: "dart",
  },
  {
    slug: "django",
    name: "django",
    isPublished: true,
    // coverImage: "",
    tags: ["django"],
    relatedPosts: [""],
    shortDescription: "django",
  },
  {
    slug: "docker",
    name: "docker",
    isPublished: true,
    // coverImage: "",
    tags: ["docker"],
    relatedPosts: [""],
    shortDescription: "docker",
  },
  {
    slug: "flask",
    name: "flask",
    isPublished: true,
    // coverImage: "",
    tags: ["flask"],
    relatedPosts: [""],
    shortDescription: "flask",
  },
  {
    slug: "flutter",
    name: "flutter",
    isPublished: true,
    // coverImage: "",
    tags: ["flutter"],
    relatedPosts: [""],
    shortDescription: "flutter",
  },
  {
    slug: "GCP",
    name: "GCP",
    isPublished: true,
    // coverImage: "",
    tags: ["GCP"],
    relatedPosts: [""],
    shortDescription: "GCP",
  },
  {
    slug: "gitlab-ci-cd",
    name: "gitlab-ci-cd",
    isPublished: true,
    // coverImage: "",
    tags: ["gitlab-ci-cd"],
    relatedPosts: [""],
    shortDescription: "gitlab-ci-cd",
  },
  {
    slug: "git",
    name: "git",
    isPublished: true,
    // coverImage: "",
    tags: ["git"],
    relatedPosts: [""],
    shortDescription: "git",
  },
  {
    slug: "go",
    name: "go",
    isPublished: true,
    // coverImage: "",
    tags: ["go"],
    relatedPosts: [""],
    shortDescription: "go",
  },
  {
    slug: "heroku-django",
    name: "heroku-django",
    isPublished: true,
    // coverImage: "",
    tags: ["heroku-django"],
    relatedPosts: [""],
    shortDescription: "heroku-django",
  },
  {
    slug: "js",
    name: "js",
    isPublished: true,
    // coverImage: "",
    tags: ["js"],
    relatedPosts: [""],
    shortDescription: "js",
  },
  {
    slug: "LetsEncrypt-certbot",
    name: "LetsEncrypt-certbot",
    isPublished: true,
    // coverImage: "",
    tags: ["LetsEncrypt-certbot"],
    relatedPosts: [""],
    shortDescription: "LetsEncrypt-certbot",
  },
  {
    slug: "linux",
    name: "linux",
    isPublished: true,
    // coverImage: "",
    tags: ["linux"],
    relatedPosts: [""],
    shortDescription: "linux",
  },
  {
    slug: "live_from_local",
    name: "live_from_local",
    isPublished: true,
    // coverImage: "",
    tags: ["live_from_local"],
    relatedPosts: [""],
    shortDescription: "live_from_local",
  },
  // {
  //   slug: "md_file",
  //   name: "md_file",
  //   isPublished: true,
  //   // coverImage: "",
  //   tags: ["md_file"],
  //   relatedPosts: [""],
  //   shortDescription: "md_file",
  // },
  {
    slug: "mongo",
    name: "mongo",
    isPublished: true,
    // coverImage: "",
    tags: ["mongo"],
    relatedPosts: [""],
    shortDescription: "mongo",
  },
  {
    slug: ".my_bash",
    name: ".my_bash",
    isPublished: true,
    // coverImage: "",
    tags: [".my_bash"],
    relatedPosts: [""],
    shortDescription: ".my_bash",
  },
  {
    slug: "mysql",
    name: "mysql",
    isPublished: true,
    // coverImage: "",
    tags: ["mysql"],
    relatedPosts: [""],
    shortDescription: "mysql",
  },
  {
    slug: "nginx",
    name: "nginx",
    isPublished: true,
    // coverImage: "",
    tags: ["nginx"],
    relatedPosts: [""],
    shortDescription: "nginx",
  },
  {
    slug: "postgresql",
    name: "postgresql",
    isPublished: true,
    // coverImage: "",
    tags: ["postgresql"],
    relatedPosts: [""],
    shortDescription: "postgresql",
  },
  {
    slug: "python",
    name: "python",
    isPublished: true,
    // coverImage: "",
    tags: ["python"],
    relatedPosts: [""],
    shortDescription: "python",
  },
  {
    slug: "react",
    name: "react",
    isPublished: true,
    // coverImage: "",
    tags: ["react"],
    relatedPosts: [""],
    shortDescription: "react",
  },
  {
    slug: "setup-ubuntu",
    name: "setup-ubuntu",
    isPublished: true,
    // coverImage: "",
    tags: ["setup-ubuntu"],
    relatedPosts: [""],
    shortDescription: "setup-ubuntu",
  },
  {
    slug: "supervisor",
    name: "supervisor",
    isPublished: true,
    // coverImage: "",
    tags: ["supervisor"],
    relatedPosts: [""],
    shortDescription: "supervisor",
  },
  {
    slug: "the-linux-command-line",
    name: "the-linux-command-line",
    isPublished: true,
    // coverImage: "",
    tags: ["the-linux-command-line"],
    relatedPosts: [""],
    shortDescription: "the-linux-command-line",
  },
  {
    slug: "vim",
    name: "vim",
    isPublished: true,
    // coverImage: "",
    tags: ["vim"],
    relatedPosts: [""],
    shortDescription: "vim",
  },
  {
    slug: "vs-code",
    name: "vs-code",
    isPublished: true,
    // coverImage: "",
    tags: ["vs-code"],
    relatedPosts: [""],
    shortDescription: "vs-code",
  },
  {
    slug: "vue",
    name: "vue",
    isPublished: true,
    // coverImage: "",
    tags: ["vue"],
    relatedPosts: [""],
    shortDescription: "vue",
  },
];

export default POST;
