const POST = [
  {
    slug: "analytics",
    name: "Analytics",
    isPublished: true,
    coverImage: "",
    tags: ["analytics"],
    relatedPosts: [""],
    shortDescription: `Google and Facebook analytics.`,
  },
  {
    slug: "android-studio",
    name: "Android studio Install and Configuration",
    isPublished: true,
    coverImage: "",
    tags: ["android-studio"],
    relatedPosts: [""],
    shortDescription: `To Install and configuring android studio you can see official doc.`,
  },
  {
    slug: "bash",
    name: "bash",
    isPublished: true,
    coverImage: "",
    tags: ["bash"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "c-sharp",
    name: "c-sharp",
    isPublished: true,
    coverImage: "",
    tags: ["c-sharp"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "crontab",
    name: "crontab",
    isPublished: true,
    coverImage: "",
    tags: ["crontab"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "cython",
    name: "cython",
    isPublished: true,
    coverImage: "",
    tags: ["cython"],
    relatedPosts: [""],
    shortDescription: `cython`,
  },
  {
    slug: "dart",
    name: "dart",
    isPublished: true,
    coverImage: "",
    tags: ["dart"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "digitalocean-python-postgresql",
    name: "digitalocean-python-postgresql",
    isPublished: true,
    coverImage: "",
    tags: ["digitalocean-python-postgresql"],
    relatedPosts: [""],
    shortDescription: `digitalocean python postgresql`,
  },
  {
    slug: "django",
    name: "django",
    isPublished: true,
    coverImage: "",
    tags: ["django"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "docker",
    name: "docker",
    isPublished: true,
    coverImage: "",
    tags: ["docker"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "flask",
    name: "flask",
    isPublished: true,
    coverImage: "",
    tags: ["flask"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "flutter",
    name: "flutter",
    isPublished: true,
    coverImage: "",
    tags: ["flutter"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "gcp",
    name: "gcp",
    isPublished: true,
    coverImage: "",
    tags: ["gcp"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "gitlab-ci-cd",
    name: "gitlab-ci-cd",
    isPublished: true,
    coverImage: "",
    tags: ["gitlab-ci-cd"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "git",
    name: "git",
    isPublished: true,
    coverImage: "",
    tags: ["git"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "go",
    name: "go",
    isPublished: true,
    coverImage: "",
    tags: ["go"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "heroku-django",
    name: "heroku-django",
    isPublished: true,
    coverImage: "",
    tags: ["heroku-django"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "image-converter",
    name: "image converter",
    isPublished: true,
    coverImage: "",
    tags: ["image", "converter"],
    relatedPosts: [""],
    shortDescription: `image converter`,
  },
  {
    slug: "js",
    name: "js",
    isPublished: true,
    coverImage: "",
    tags: ["js"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "kubernetes",
    name: "Kubernetes",
    isPublished: true,
    coverImage: "",
    tags: ["kubernetes"],
    relatedPosts: [""],
    shortDescription: `kubernetes`,
  },
  {
    slug: "LetsEncrypt-certbot",
    name: "LetsEncrypt-certbot",
    isPublished: true,
    coverImage: "",
    tags: ["LetsEncrypt-certbot"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "linux",
    name: "linux",
    isPublished: true,
    coverImage: "",
    tags: ["linux"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "live-from-local",
    name: "live-from-local",
    isPublished: true,
    coverImage: "",
    tags: ["server", "local"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "migration-and-backup",
    name: "migration-and-backup",
    isPublished: true,
    coverImage: "",
    tags: ["migration", "backup", "export", "import"],
    relatedPosts: [""],
    shortDescription: `Export and import data from database`,
  },
  // {
  //   slug: "md_file",
  //   name: "md_file",
  //   isPublished: true,
  // coverImage: "",
  //   tags: ["md_file"],
  //   relatedPosts: [""],
  //   shortDescription: shortDescription`,
  // },
  {
    slug: "mongo",
    name: "mongo",
    isPublished: true,
    coverImage: "",
    tags: ["mongo"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "mysql",
    name: "mysql",
    isPublished: true,
    coverImage: "",
    tags: ["mysql"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "nginx",
    name: "nginx",
    isPublished: true,
    coverImage: "",
    tags: ["nginx"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "postgresql",
    name: "postgresql",
    isPublished: true,
    coverImage: "",
    tags: ["postgresql"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "python",
    name: "python",
    isPublished: true,
    coverImage: "",
    tags: ["python"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "react",
    name: "react",
    isPublished: true,
    coverImage: "",
    tags: ["react"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "server-security",
    name: "server security",
    isPublished: true,
    coverImage: "",
    tags: ["server", "security"],
    relatedPosts: [""],
    shortDescription: `server-security`,
  },
  {
    slug: "setup-ubuntu",
    name: "setup-ubuntu",
    isPublished: true,
    coverImage: "",
    tags: ["setup-ubuntu"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "supervisor",
    name: "supervisor",
    isPublished: true,
    coverImage: "",
    tags: ["supervisor"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "the-linux-command-line",
    name: "the-linux-command-line",
    isPublished: true,
    coverImage: "",
    tags: ["the-linux-command-line"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "travis-ci",
    name: "travis-ci",
    isPublished: true,
    coverImage: "",
    tags: ["travis-ci"],
    relatedPosts: [""],
    shortDescription: `travis-ci`,
  },
  {
    slug: "ts",
    name: "ts",
    isPublished: true,
    coverImage: "",
    tags: ["ts"],
    relatedPosts: [""],
    shortDescription: `ts`,
  },
  {
    slug: "vim",
    name: "vim",
    isPublished: true,
    coverImage: "",
    tags: ["vim"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "vs-code",
    name: "vs-code",
    isPublished: true,
    coverImage: "",
    tags: ["vs-code"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
  {
    slug: "vue",
    name: "vue",
    isPublished: true,
    coverImage: "",
    tags: ["vue"],
    relatedPosts: [""],
    shortDescription: `shortDescription`,
  },
];

export default POST;
